name: CI and Release

on:
  push:
    branches: [main, develop]
    tags:
      - "v*"
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_release:
        description: "Force release even if tag exists"
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        exclude:
          - os: macos-latest
            rust: beta
          - os: windows-latest
            rust: beta

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Test binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            ./target/release/pori.exe --version
          else
            ./target/release/pori --version
          fi

  check-version-and-release:
    name: Version Check and Release
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    outputs:
      should_release: ${{ steps.version_check.outputs.should_release }}
      version: ${{ steps.version_check.outputs.version }}
      raw_version: ${{ steps.version_check.outputs.raw_version }}
      changelog_content: ${{ steps.changelog.outputs.content }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version and check release conditions
        id: version_check
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger
            VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
            FORCE_RELEASE="${{ github.event.inputs.force_release }}"
            echo "Manual trigger with force_release: $FORCE_RELEASE"
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # Tag push
            TAG_VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${TAG_VERSION#v}
            FORCE_RELEASE="true"
            echo "Tag push detected: $TAG_VERSION"
          else
            # Push to main
            VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
            FORCE_RELEASE="false"
            echo "Push to main detected"
          fi

          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "raw_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: v$VERSION"

          # Check if tag exists
          if git rev-parse --verify "refs/tags/v$VERSION" >/dev/null 2>&1; then
            TAG_EXISTS="true"
            echo "Tag v$VERSION already exists"
          else
            TAG_EXISTS="false"
            echo "Tag v$VERSION does not exist"
          fi

          # Determine if we should release
          if [ "$TAG_EXISTS" = "false" ] || [ "$FORCE_RELEASE" = "true" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "Will proceed with release"
            
            # Create tag if it doesn't exist
            if [ "$TAG_EXISTS" = "false" ]; then
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git tag -a "v$VERSION" -m "Release v$VERSION"
              git push origin "v$VERSION"
              echo "Created and pushed tag: v$VERSION"
            fi
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "Skipping release - tag exists and not forced"
          fi

      - name: Extract changelog for current version
        id: changelog
        if: steps.version_check.outputs.should_release == 'true'
        run: |
          # Extract changelog section for current version
          CHANGELOG_CONTENT=$(awk '/^## \['"${{ steps.version_check.outputs.raw_version }}"'\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md)
          if [ -z "$CHANGELOG_CONTENT" ]; then
            echo "No changelog found for version ${{ steps.version_check.outputs.raw_version }}"
            CHANGELOG_CONTENT="See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details."
          fi
          # Escape content for GitHub Actions
          CHANGELOG_CONTENT="${CHANGELOG_CONTENT//'%'/'%25'}"
          CHANGELOG_CONTENT="${CHANGELOG_CONTENT//$'\n'/'%0A'}"
          CHANGELOG_CONTENT="${CHANGELOG_CONTENT//$'\r'/'%0D'}"
          echo "content=$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.target }}
    needs: check-version-and-release
    if: needs.check-version-and-release.outputs.should_release == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-x86_64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: linux-x86_64-musl
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-aarch64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: darwin-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: darwin-aarch64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: windows-x86_64
            extension: .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'x86_64-unknown-linux-musl' || matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build binary
        shell: bash
        run: |
          if [ "${{ matrix.target }}" = "x86_64-unknown-linux-gnu" ] || [ "${{ matrix.target }}" = "x86_64-pc-windows-msvc" ] || [ "${{ matrix.target }}" = "x86_64-apple-darwin" ] || [ "${{ matrix.target }}" = "aarch64-apple-darwin" ]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cross build --release --target ${{ matrix.target }}
          fi

      - name: Prepare release asset
        shell: bash
        run: |
          mkdir -p release-assets
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/pori${{ matrix.extension }} release-assets/
            cd release-assets
            powershell -Command "Compress-Archive -Path 'pori${{ matrix.extension }}' -DestinationPath 'pori-${{ matrix.name }}.zip'"
          else
            cp target/${{ matrix.target }}/release/pori release-assets/
            cd release-assets
            tar -czf pori-${{ matrix.name }}.tar.gz pori
          fi

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: pori-${{ matrix.name }}
          path: release-assets/pori-${{ matrix.name }}.*

  release:
    name: Create Release
    needs: [check-version-and-release, build]
    if: needs.check-version-and-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Generate checksums
        run: |
          cd release-assets
          sha256sum * > SHA256SUMS
          cat SHA256SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-version-and-release.outputs.version }}
          name: Release ${{ needs.check-version-and-release.outputs.version }}
          body: |
            ## Changes

            ${{ needs.check-version-and-release.outputs.changelog_content }}

            ## Downloads

            | Platform | Architecture | Download |
            |----------|--------------|----------|
            | Linux | x86_64 | [pori-linux-x86_64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ needs.check-version-and-release.outputs.version }}/pori-linux-x86_64.tar.gz) |
            | Linux | x86_64 (musl) | [pori-linux-x86_64-musl.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ needs.check-version-and-release.outputs.version }}/pori-linux-x86_64-musl.tar.gz) |
            | Linux | ARM64 | [pori-linux-aarch64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ needs.check-version-and-release.outputs.version }}/pori-linux-aarch64.tar.gz) |
            | macOS | x86_64 | [pori-darwin-x86_64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ needs.check-version-and-release.outputs.version }}/pori-darwin-x86_64.tar.gz) |
            | macOS | ARM64 | [pori-darwin-aarch64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ needs.check-version-and-release.outputs.version }}/pori-darwin-aarch64.tar.gz) |
            | Windows | x86_64 | [pori-windows-x86_64.zip](https://github.com/${{ github.repository }}/releases/download/${{ needs.check-version-and-release.outputs.version }}/pori-windows-x86_64.zip) |

            ## Installation

            ### Linux/macOS Quick Install
            ```bash
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/release/install.sh | bash
            ```

            ### Manual Installation
            1. Download the appropriate binary for your platform
            2. Extract the archive
            3. Move the binary to a directory in your PATH
            4. Make it executable (Linux/macOS): `chmod +x pori`

            ## Verification

            Verify the integrity of downloaded files using the provided checksums:
            ```bash
            sha256sum -c SHA256SUMS
            ```
          files: |
            release-assets/*
          draft: false
          prerelease: false
          generate_release_notes: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-install:
    name: Test Installation Script
    needs: [check-version-and-release, release]
    if: needs.check-version-and-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test installation script
        run: |
          chmod +x release/install.sh
          # Test dry run
          bash release/install.sh --dry-run
