name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-x86_64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: linux-x86_64-musl
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-aarch64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: darwin-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: darwin-aarch64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: windows-x86_64
            extension: .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare release asset
        shell: bash
        run: |
          mkdir -p release-assets
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/tunnel-client${{ matrix.extension }} release-assets/
            cd release-assets
            zip tunnel-client-${{ matrix.name }}.zip tunnel-client${{ matrix.extension }}
          else
            cp target/${{ matrix.target }}/release/tunnel-client release-assets/
            cd release-assets
            tar -czf tunnel-client-${{ matrix.name }}.tar.gz tunnel-client
          fi

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: tunnel-client-${{ matrix.name }}
          path: release-assets/tunnel-client-${{ matrix.name }}.*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Generate checksums
        run: |
          cd release-assets
          sha256sum * > SHA256SUMS
          cat SHA256SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Changes

            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.

            ## Downloads

            | Platform | Architecture | Download |
            |----------|--------------|----------|
            | Linux | x86_64 | [tunnel-client-linux-x86_64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/tunnel-client-linux-x86_64.tar.gz) |
            | Linux | x86_64 (musl) | [tunnel-client-linux-x86_64-musl.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/tunnel-client-linux-x86_64-musl.tar.gz) |
            | Linux | ARM64 | [tunnel-client-linux-aarch64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/tunnel-client-linux-aarch64.tar.gz) |
            | macOS | x86_64 | [tunnel-client-darwin-x86_64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/tunnel-client-darwin-x86_64.tar.gz) |
            | macOS | ARM64 | [tunnel-client-darwin-aarch64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/tunnel-client-darwin-aarch64.tar.gz) |
            | Windows | x86_64 | [tunnel-client-windows-x86_64.zip](https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/tunnel-client-windows-x86_64.zip) |

            ## Installation

            ### Linux/macOS Quick Install
            ```bash
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/release/install.sh | bash
            ```

            ### Manual Installation
            1. Download the appropriate binary for your platform
            2. Extract the archive
            3. Move the binary to a directory in your PATH
            4. Make it executable (Linux/macOS): `chmod +x tunnel-client`

            ## Verification

            Verify the integrity of downloaded files using the provided checksums:
            ```bash
            sha256sum -c SHA256SUMS
            ```
          files: |
            release-assets/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-install:
    name: Test Installation Script
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test installation script
        run: |
          chmod +x release/install.sh
          # Test dry run
          bash release/install.sh --dry-run
